artifact_uri: file:///home/mle-user/mle_projects/mle-mlflow/mlflow_experiments_store/0/0098e51e101e457cb25dcb24326f1e3d/artifacts
end_time: 1725090428327
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 0098e51e101e457cb25dcb24326f1e3d
run_name: Default
run_uuid: 0098e51e101e457cb25dcb24326f1e3d
source_name: ''
source_type: 4
source_version: ''
start_time: 1725090428319
status: 3
tags: []
user_id: mle-user
